### ISSUE TITLE
纯属个人强迫症

### ISSUE THREAD

**Issue by laksg2009** [jackwaylong/AndroidSocketCore#1]
NetworkMonitorReceiver类

1.
private static final LinkedList<NetworkMonitor> mObservable = new LinkedList();
改为:
private static final LinkedList<NetworkMonitor> mObservable = new LinkedList<>();
这样就不会有橙色的警告了.看着也舒服了...哈哈

2.
还有if (networkMonitors != null) {
报警告,此判断语句永远为真,我认真看了看发现也确实是这样.
如果改成这样可以吗????
private void notifyNetworkMonitor(boolean success, int type, String reason) {
        synchronized (mObservable) {
            for (NetworkMonitor chine : mObservable) {
                if (success) {
                    chine.onConnect(type);
                } else {
                    chine.onDisconnected(reason);
                }
            }
        }
    }

3.int type = intent.getIntExtra(ConnectivityManager.EXTRA_NETWORK_TYPE, -1);
这个方法没有指明API使用级别为16以上.我设备是14,所以这里老是会判断为无网络.这是错误的判断.

**Comment by laksg2009** [comment]
SocketChannelClient类
registerNetworkMonitor()函数,会存在场景问题.
例如我创建socket后.我想点击连接的时候才去连接这个socket,因为registerNetworkMonitor这个函数最终会回调startReconnect这个函数,所以导致我没有电开始链接socket的情况下会一直死循环重链.

**Comment by jacklongway** [comment]
@laksg2009 
第一个问题: `private static final LinkedList mObservable = new LinkedList();`  等价于`private static final LinkedList mObservable = new LinkedList<>();`  在修复版本中，已经说明，可以去看看详细的回答

第二个问题：之所以那么处理有几个原因：
1.  保证程序的稳定性，基础性的东西，即使看上去不为空，但是最好还是判空处理，避免暴力反射，code attack等问题的出现，这里注意就好。
2.  之所以不用迭代器直接处理，这里考虑数组与链表的差异性，注册直接链表，这个动作是插入，性能优越于数组，通知是一种查询操作，数组是线性存储的，查找性能优越于链表，所以这里用空间换时间的方式，实现调优处理，这里注意一下就好。

第三个问题: int type = `intent.getIntExtra(ConnectivityManager.EXTRA_NETWORK_TYPE,` -1)`; 这个方法`apilevel 1`就有了，这个是`intent`里面的方法，自行查阅官方文档查看属于的api level。

第四个问题: SocketChannelClient 在一些**场景**的问题，确实存在，**1.0.1**版本已经修复，修复版本中也添加了详细注释，可以去看看。最后还说一下，一般socket场景的应用都是需要长时间后台运行的，可能涉及到后台保活的需求，可以查看我写的保活服务基础组件，链接: [daemon](https://github.com/jackwaylong/Daemon)
