### ISSUE TITLE
发送数据太大得问题

### ISSUE THREAD

**Issue by laksg2009** [jackwaylong/AndroidSocketCore#2]
发送数据太大数据发送不全对方无法获取全部数据
百度搜索后找到解决办法(但不知为何要sleep),
此方法在SocketChannelClient类里,.
void writeMessageToServer(byte[] msg) throws Exception {
        if (isConnected()) {
//            mSocketChannelClient.write(ByteBuffer.wrap(msg));
            ByteBuffer wrap = ByteBuffer.wrap(msg);
            if (wrap != null) {
                while (wrap.hasRemaining()) {
                    int len = mSocketChannelClient.write(wrap);
                    Thread.sleep(500);
                    if(len < 0){
                        throw new Exception();
                    }
                    if(len == 0){
                        break;
                    }
                }
            }
        }
    }

测试环境,图片转Base64后(700多KB)发送给服务器.就会出现这个问题.系统版本安卓4.0.1

**Comment by jacklongway** [comment]
@laksg2009 之前跟你说过，这个库最适合小数据量实时通讯需求，并不太适合数据量太大的场景，图片本来就比较大，转换成base64编码其实变得更大了，这样一来，数据量大，如果长连接通道只要有一点抖动，可能就导致数据异常，从而可能导致服务器接收异常。所以建议用专门的http通道上传图片，然后传输图片的地址信息，这只是目前的建议，我会考虑是否加上对传输数据量大的支持，但是在网络稳定情况下，即使传输图片数据流应该也没问题的，是不是服务器读取方式有问题，最好在提issue的时候，能够把服务端与客户端的日志都上传上来，这样我好定位问题的原因。
