### ISSUE TITLE
项目无法正常运行

### ISSUE THREAD

**Issue by laksg2009** [jackwaylong/AndroidSocketCore#3]
1):R文件引用包位置错误导致
2):一直报空,要么判空下,要么把start提前在各种监听之前运行.
3):发送数据编码无法改变.
4):ping的数据很不稳定,服务器不是每隔X秒后收到ping的数据,而是不确定时间收到不确定的ping条数据........
5):如果服务器主动端口连接的话会导致SocketChannelClient类中的while (iterator.hasNext())死循环.

**Comment by jacklongway** [comment]
@laksg2009 
1):R文件引用包位置错误导致
这个clean一下，或者自己检查一下r类与引用的位置是否对，或者资源文件是否存在。
2):一直报空,要么判空下,要么把start提前在各种监听之前运行.
这个具体问题在哪，请把把问题的log贴出来
3):发送数据编码无法改变.
这个下一版本加上编码支持，其实现在传输的byte，这个编码调用方可以自由设置，然后生成对应byte数组的。并且该库只是一个core，提供的都是byte，具体的业务接入，可以按照具体的需求。
4):ping的数据很不稳定,服务器不是每隔X秒后收到ping的数据,而是不确定时间收到不确定的ping条数据........
这个确实不确定的，不是不稳定，ping是有触发条件的，为了减轻服务器的压力与网络稳定性问题，代码里面有个活动最后时间，是否发送ping数据是根据当前时间与活动时间的差值是否满足ping条件决定的。
5):如果服务器主动端口连接的话会导致SocketChannelClient类中的while (iterator.hasNext())死循环.
服务端主动连接客户端，这个描述确定没问题，一般都是客户端主动连接服务端

**Comment by laksg2009** [comment]
@jackwaylong 如果服务器主动断开与客户端的连接的话会导致SocketChannelClient类中的while (iterator.hasNext())死循环.(不好意思打错字了).
1):R文件引用包位置错误导致,这个问题我clean过了也是一样,而且你点击布局文件是可以正确跳转到布局的.我的Android Studio版本是最新的稳定版,你可以试试.
